### ISSUE TITLE
Sub-tasks should move with parent

### ISSUE THREAD

**Issue by somelinguist** [coddx-hq/coddx-alpha#18]
### Expected behavior: Moving or reordering a task with sub-tasks should move the entire group.

```
### Todo

- [ ] Markdown links for File or URL  
- [ ] Rename Git Repos  
  - [ ] Update Readme, Docs  
  - [ ] Update all URLs  

### In Progress



```

#### Moving `Rename Git Repos` to In Progress should result in:

```
### Todo

- [ ] Markdown links for File or URL  


#### In Progress

- [ ] Rename Git Repos  
  - [ ] Update Readme, Docs  
  - [ ] Update all URLs  


```

#### Reordering, dragging `Rename Git Repos`, should result in:

```
### Todo

- [ ] Rename Git Repos  
  - [ ] Update Readme, Docs  
  - [ ] Update all URLs  
- [ ] Markdown links for File or URL  

### In Progress



```

#### Moving `Rename Git Repos` to In Progress:

```
### Todo

- [ ] Markdown links for File or URL  
  - [ ] Update Readme, Docs  
  - [ ] Update all URLs  

### In Progress

- [ ] Rename Git Repos  


```

#### Reordering, dragging `Rename Git Repos`:

```
### Todo

- [ ] Rename Git Repos  
- [ ] Markdown links for File or URL  
  - [ ] Update Readme, Docs  
  - [ ] Update all URLs  

### In Progress



```
